- name: check hadoop if exists
  stat:
    path: /opt/hadoop
  register: hadoop_archive
- when: not hadoop_archive.stat.exists
  block:
    - name: unarchive hadoop 
      unarchive: src={{ hadoop_soft_name }} dest=/opt/ copy=yes
    - name: add link
      file:
        state: link
        src: "/opt/{{ hadoop_name }}"
        dest: /opt/hadoop
- name: copy config
  copy: 
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'core-site.xml', dest: '{{ hadoop_path }}/etc/hadoop/' }
    - { src: 'hdfs-site.xml', dest: '{{ hadoop_path }}/etc/hadoop/' }
    - { src: 'yarn-site.xml', dest: '{{ hadoop_path }}/etc/hadoop/' }
    - { src: 'mapred-site.xml', dest: '{{ hadoop_path }}/etc/hadoop/' }
    - { src: 'workers', dest: '{{ hadoop_path }}/etc/hadoop/' }
    - { src: 'hadoop-env.sh', dest: '{{ hadoop_path }}/etc/hadoop/' }
